name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Prepare package.json
      run: cp package-render.json package.json
    - name: Install dependencies
      run: npm ci
    - name: Check for syntax errors
      run: node -c server.js
    - name: Run server for 5 seconds to verify startup
      run: |
        node -e "
        const { spawn } = require('child_process');
        const server = spawn('node', ['server.js']);
        
        server.stdout.on('data', (data) => {
          console.log(\`stdout: \${data}\`);
        });
        
        server.stderr.on('data', (data) => {
          console.error(\`stderr: \${data}\`);
        });
        
        setTimeout(() => {
          server.kill('SIGINT');
          process.exit(0);
        }, 5000);
        "
